spring.application.name=demo
spring.mvc.api-version.use.query-parameter=version
spring.mvc.api-version.supported=1,2
spring.mvc.api-version.default=1


# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate  # options: validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



